### ISSUE TITLE
Project example to test the plugin

### ISSUE THREAD

**Issue by apieraf** [davidetaibi/sonarqube-anti-patterns-code-smells#1]
Hi, 

I'm interested in test and use your plugin. I installed it in my SonarQube 5.5, but in my projects the plugin didn't find any issue. Do you have any project to test the plugin appropriately?

Thanks in advance

**Comment by cuuzis** [comment]
A sample project is now included in the [integration tests](https://github.com/davidetaibi/sonarqube-anti-patterns-code-smells/tree/master/src/test/projects)
