### ISSUE TITLE
Caused by: java.io.FileNotFoundException: The source does not exist labels

### ISSUE THREAD

**Issue by sasah** [davidetaibi/sonarqube-anti-patterns-code-smells#3]
20:14:17 [test] INFO: Sensor CodeSmellsAntiPatternsSensor [CodeSmellsAntiPatterns]
20:14:17 [test] INFO: PadlModuleDir labels
20:14:17 [test] INFO: ------------------------------------------------------------------------
20:14:17 [test] INFO: EXECUTION FAILURE
20:14:17 [test] INFO: ------------------------------------------------------------------------
20:14:17 [test] INFO: Total time: 18.162s
20:14:17 [test] INFO: Final Memory: 60M/779M
20:14:17 [test] INFO: ------------------------------------------------------------------------
20:14:17 [test] ERROR: Error during SonarQube Scanner execution
20:14:17 [test] java.lang.RuntimeException: java.io.FileNotFoundException: The source does not exist labels
20:14:17 [test] 	at padl.creator.javafile.eclipse.CompleteJavaFileCreator.<init>(CompleteJavaFileCreator.java:86)
20:14:17 [test] 	at it.unibz.sonarqube_plugin.CodeSmellsAntiPatternsSensor.analyseCodeLevelModelFromJavaSourceFilesEclipse(CodeSmellsAntiPatternsSensor.java:312)
20:14:17 [test] 	at it.unibz.sonarqube_plugin.CodeSmellsAntiPatternsSensor.analyse(CodeSmellsAntiPatternsSensor.java:93)
20:14:17 [test] 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
20:14:17 [test] 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
20:14:17 [test] 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:74)
20:14:17 [test] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
20:14:17 [test] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
20:14:17 [test] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
20:14:17 [test] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
20:14:17 [test] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
20:14:17 [test] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:255)
20:14:17 [test] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
20:14:17 [test] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
20:14:17 [test] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
20:14:17 [test] 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
20:14:17 [test] 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
20:14:17 [test] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
20:14:17 [test] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
20:14:17 [test] 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
20:14:17 [test] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
20:14:17 [test] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
20:14:17 [test] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:14:17 [test] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:14:17 [test] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:14:17 [test] 	at java.lang.reflect.Method.invoke(Method.java:498)
20:14:17 [test] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
20:14:17 [test] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
20:14:17 [test] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
20:14:17 [test] 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
20:14:17 [test] 	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
20:14:17 [test] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
20:14:17 [test] 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
20:14:17 [test] Caused by: java.io.FileNotFoundException: The source does not exist labels
20:14:17 [test] 	at padl.creator.javafile.eclipse.CompleteJavaFileCreator.<init>(CompleteJavaFileCreator.java:87)
20:14:17 [test] 	... 32 more
20:14:17 [test] ERROR: 
20:14:17 [test] ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

**Comment by cuuzis** [comment]
Thanks @sasah ! Can you please share the source code you analyzed? I cannot seem to replicate the error

**Comment by cuuzis** [comment]
Different source paths should work with [release 0.7](https://github.com/davidetaibi/sonarqube-anti-patterns-code-smells/releases/tag/0.7)
