### ISSUE TITLE
padl.generator.helper.ModelGenerator exception issue

### ISSUE THREAD

**Issue by SimonLollamen** [davidetaibi/sonarqube-anti-patterns-code-smells#9]
Hi,

when i try to run the sonar scanner in some project the sonar scanner stuck on this error on loop

INFO: Sensor Code Smell Anti-pattern Sensor [codesmellsantipatterns]
util.lang.ConcreteReceiverGuard reports a runtime deprecation: calling method "padl.kernel.impl.CodeLevelModel.create()" from class "it.unibz.sonarqube.plugin.CodeSmellsAntiPatternsSensor"
Please use the methods in "padl.generator.helper.ModelGenerator" to obtain code-level models.

I use the 0,7 version of the codesmell plugin

EDIT: Solved.

**Comment by mattiamonari** [comment]
How did you solve this?
